# Generated by Django 6.0.5 on 2026-06-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='rollmo',
            new_name='rollno',
        ),
        migrations.RenameField(
            model_name='students_history',
            old_name='rollmo',
            new_name='rollno',
        ),
    ]
