# Generated by Django 6.0.5 on 2026-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_rollmo_students_rollno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='students',
            name='rollno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students_history',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='students_history',
            name='rollno',
            field=models.IntegerField(),
        ),
    ]
