# Generated by Django 6.0.5 on 2026-05-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('dept', models.CharField(max_length=100)),
                ('sal', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
