# Generated by Django 6.0.5 on 2026-06-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo_history',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
