# Generated by Django 6.0.5 on 2026-05-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proffesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sal', models.IntegerField()),
                ('branch', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=254)),
                ('exp', models.IntegerField()),
            ],
        ),
    ]
