# Generated by Django 6.0.5 on 2026-05-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('sal', models.IntegerField()),
                ('exp', models.IntegerField()),
            ],
        ),
    ]
